app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, SelectField, PasswordField, ValidationError
from wtforms.validators import DataRequired, EqualTo, Length
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.fields.html5 import DateField

from .. import db
from ..models import City

class KostFormUser (FlaskForm):
    """
    Form untuk admin menambah / edit kost
    """

    # def city_query():
    #     return db.session.query(City).all()

    Kname = StringField('Nama Kost', validators=[DataRequired()])
    Kaddress = StringField('Alamat Kost', validators=[DataRequired()])
    # Kota = QuerySelectField('Kota', query_factory=city_query,
    #                         allow_blank=False,
    #                         get_pk=lambda a: a.Cid,
    #                         get_label=lambda a: a.kota)
    Kota = SelectField('Kota Tempat Tinggal', validators=[DataRequired()], choices=[
                                (1, 'Jakarta Pusat'),
                                (2, 'Jakarta Barat'),
                                (3, 'Jakarta Selatan'),
                                (4, 'Jakarta Timur'),
                                (5, 'Jakarta Utara'),
                                (6, 'Kepulauan Seribu')], coerce=int)
    Kprice = IntegerField('Harga per-Bulan', validators=[DataRequired()])
    Ktype = SelectField('Jenis Kost', validators=[DataRequired()], choices=[
                                ('Kost Laki-Laki', 'Kost Laki-Laki'),
                                ('Kost Perempuan', 'Kost Perempuan'),
                                ('Kost Pasutri', 'Kost Pasutri')])
    Kphone = StringField('Nomor Telepon', validators=[DataRequired()])
    submit = SubmitField('Simpan')

class EditProfilUser (FlaskForm):
    """
    Edit profil
    """
    username = StringField('Username', validators=[DataRequired(), Length(min=4, max=60)])
    nama_depan = StringField('Nama Depan', validators=[DataRequired(), Length(max=60)])
    nama_belakang = StringField('Nama Belakang', validators=[DataRequired(), Length(max=60)])
    kota = SelectField('Kota Tempat Tinggal', validators=[DataRequired()], choices=[
                                (1, 'Jakarta Pusat'),
                                (2, 'Jakarta Barat'),
                                (3, 'Jakarta Selatan'),
                                (4, 'Jakarta Timur'),
                                (5, 'Jakarta Utara'),
                                (6, 'Kepulauan Seribu')], coerce=int)
    tanggal_lahir = DateField('Tanggal Lahir', format='%Y-%m-%d', validators=[DataRequired()])
    submit = SubmitField('Simpan')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
import jsonpickle

from . import user
from forms import KostFormUser, EditProfilUser
from .. import db
from ..models import User, Kost, City

def check_admin():
    """
    Hanya untuk user biasa
    """
    if current_user.is_admin:
        abort(403)

@user.route('/profil/<username>')
@login_required
def profil(username):
    """
    Render template profil pada route /profil
    """
    # users = User.query.with_entities(User.username)
    punyakost = db.session.query(Kost).filter(Kost.user_id==current_user.id, Kost.Kverified==True)
    # punyakost = db.session.query(Kost.Kname, Kost.Kaddress, Kost.city_Cid,
    #                             Kost.Kphone).filter(Kost.user_id==current_user.id, Kost.Kverified==True)
    result = punyakost.all()

    query = db.session.query(Kost).filter(Kost.Kverified==True).all()

    return render_template('user/profil.html', punyakost=punyakost, result=result, query=query, title='Profil')

@user.route('/profil/<username>/inputkost', methods=['GET', 'POST'])
@login_required
def user_add_kost(username):
    """
    Tambah kost ke database
    """
    check_admin()

    user_add_kost = True

    form = KostFormUser()
    if form.validate_on_submit():
        p_d = form.Kprice.data
        if p_d <= 300000:
            p_r = 1
        elif p_d >= 300001 and p_d <= 600000:
            p_r = 2
        elif p_d >= 600001 and p_d <= 900000:
            p_r = 3
        elif p_d >= 900001 and p_d <= 1200000:
            p_r = 4
        elif p_d >= 1200001:
            p_r = 5

        kost = Kost(Kname=form.Kname.data,
                    Kaddress=form.Kaddress.data,
                    city_Cid=form.Kota.data,
                    Kprice=form.Kprice.data,
                    Kprice_range=p_r,
                    Ktype=form.Ktype.data,
                    Kphone=form.Kphone.data,
                    user_id=current_user.id)
        try:
            # tambah kost ke database
            db.session.add(kost)
            db.session.commit()
            flash('Kost menunggu verifikasi Admin, Setelah itu akan muncul di halaman ini')
        except:
            #Apabila kost sudah pernah didaftarkan
            flash('Error: kost sudah didaftarkan')

        #redirect ke halaman kosts
        return redirect(url_for('user.profil', username=current_user.username))

    #load kost template
    return render_template('user/kosts/kost.html', action="Add",
                            user_add_kost=user_add_kost, form=form, title="Tambah Kost")

@user.route('/profil/<id>/editprofil', methods=['GET', 'POST'])
@login_required
def user_edit_profil(id):
    """
    edit profil
    """
    check_admin()

    user = User.query.get_or_404(id)
    form = EditProfilUser(obj=user)
    if form.validate_on_submit():
        user.username=form.username.data,
        user.nama_depan=form.nama_depan.data,
        user.nama_belakang=form.nama_belakang.data,
        user.kota_Cid=form.kota.data,
        user.tanggal_lahir=form.tanggal_lahir.data,
        db.session.commit()
        flash('Profil sudah berhasil diedit')

        return redirect(url_for('user.profil', username=current_user.username))

    form.tanggal_lahir.data = user.tanggal_lahir
    form.kota.data = user.kota_Cid
    form.nama_belakang.data = user.nama_belakang
    form.nama_depan = user.nama_depan
    form.username.data = user.username
    return render_template('user/edit_profil.html', action="Edit",
                            form=form, user=user, title="Edit Profil")

@user.route('/kost/<Kname>', methods=['GET', 'POST'])
@login_required
def kost_profil(Kname):

    kost = db.session.query(Kost).filter(Kost.Kname==Kname)

    return render_template('user/kosts/kost_profil.html', kost=kost, title='Profil Kost')

app/templates/user/edit_profil.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
Edit Profil
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
          <h1>Edit Profil</h1>
          <br/>
          {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/user/profil.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Profil{% endblock %}
{% block body %}
<br/>
<br/>
{{ utils.flashed_messages() }}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hallo, {{ current_user.username }}</h1>
                    <br/>
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h3 class="panel-title">Profil</h3>
                      </div>
                      <div class="panel-body">
                        <dl class="dl-horizontal">
                          <br>
                          <dt>Nama Depan :</dt>
                          <dd>{{ current_user.nama_depan }}</dd>
                          <dt>Nama Belakang :</dt>
                          <dd>{{ current_user.nama_belakang }}</dd>
                          <dt>Kota Tinggal :</dt>
                          {% if current_user.kota_Cid == 1 %}
                            <dd>Jakarta Pusat</dd>
                            {% elif current_user.kota_Cid == 2 %}
                              <dd>Jakarta Barat</dd>
                              {% elif current_user.kota_Cid == 3 %}
                                <dd>Jakarta Selatan</dd>
                                {% elif current_user.kota_Cid == 4 %}
                                  <dd>Jakarta Timur</dd>
                                  {% elif current_user.kota_Cid == 5 %}
                                    <dd>Jakarta Utara</dd>
                                    {% elif current_user.kota_Cid == 6 %}
                                      <dd>Kepulauan Seribu</dd>
                                      {% elif current_user.kota_Cid == 7 %}
                                        <dd>Tangerang Selatan</dd>
                          {% endif %}
                        </dl>
                        <hr class="intro-divider">
                        {% if result %}
                          <div class="center">
                            <table class="table table-striped table-bordered">
                              <thead>
                                <tr>
                                  <th class="text-center" width="25%"> Nama </th>
                                  <th class="text-center" width="45%"> Alamat </th>
                                  <th class="text-center" width="15%"> Telepon </th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for punya in punyakost %}
                                <tr>
                                  <td>{{ punya.Kname }}</td>
                                  <td>{{ punya.Kaddress }}, {{ punya.city.kota }} </td>
                                  <td>{{ punya.Kphone }}</td>
                                </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                          </div>
                        {% else %}
                        {% endif %}
                      </div>
                      <div class="panel-footer">
                        {% if current_user.is_admin %}
                        {% else %}
                          <a href="{{ url_for('user.user_edit_profil', id=current_user.id) }}">
                            <button type="button" class="btn btn-default">Edit Profil</button>
                          </a>
                          <a href="{{ url_for('user.user_add_kost', username=current_user.username) }}">
                            <button type="button" class="btn btn-default">Daftarkan Kostan Kamu</button>
                          </a>
                        {% endif %}
                      </div>
                    </div>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}